language: c

compiler: gcc
   
before-install:
  - git submodule update --init --recursive

install: true

stage: 
  - build
  - test

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      script: make all
    - stage: test
      script: echo test
